apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-project
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    tag: gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
