# permissions for end users to view authors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: author-viewer-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - authors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - authors/status
  verbs:
  - get
