# permissions for end users to view episodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: episode-viewer-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes/status
  verbs:
  - get
