# permissions for end users to edit episodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: episode-editor-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes/status
  verbs:
  - get
