# permissions for end users to edit rsses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rss-editor-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses/status
  verbs:
  - get
