# permissions for end users to view rsses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rss-viewer-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses/status
  verbs:
  - get
