# permissions for end users to view shows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: show-viewer-role
rules:
- apiGroups:
  - osf2f.my.domain
  resources:
  - shows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - shows/status
  verbs:
  - get
