apiVersion: osf2f.my.domain/v1alpha1
kind: Notifier
metadata:
  name: slack
spec:
  slack:
    webhook_url: https://hooks.slack.com/services/your-token
    channel: random
    username: rick
