apiVersion: v1
kind: Service
metadata:
  labels:
    app: osf2f-ui
  name: osf2f-ui
  namespace: osf2f-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: front
      nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: osf2f-ui
  sessionAffinity: None
  type: NodePort
